Repository aws-samples/jp-prototyping-blog, pull requests merged in 2023-02, with the labels that each got.

#39 add an article about ec2 mac
  blog/2023-02-01-ec2-mac-instances/ard.jpg
  blog/2023-02-01-ec2-mac-instances/dedicated-hosts.png
  blog/2023-02-01-ec2-mac-instances/index.md
  blog/2023-02-01-ec2-mac-instances/quota.png
Labels: new post

#42 Amazon Lex, Amazon Kendra のサンプルプロジェクト開発で集めた Tips
  blog/2023-02-08-lex-kendra-dev/index.md
Labels: new post

#41 マージについて追記
  .github/pull_request_template.md
Labels: enhancement

#45 EC2 mac記事にリンク追加
  blog/2023-02-01-ec2-mac-instances/index.md
Labels: miscellaneous
